name = 'Total Mayhem'
uid = 'fa-total-mayhem-138'
version = 138
copyright = 'Burnie'
description = 'Guaranteed to support Forged Alliance Forever. Introduces various novel units with new projectiles and (sound) effects. Prepare for mayhem!'
author = 'Burnie'
url = 'https://github.com/FAForever/fa-total-mayhem'
icon = '/mods/fa-total-mayhem/modicon.jpg'
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
